version: "2"
services:
  app:
    build: ./get_sd_ou
    image: erfan123a/get-sd-ou
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: siencedirect
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/db_data:/var/lib/mysql
