version: "2"
services:
  app:
    build: ./get_sd_ou
    image: erfan123a/get-sd-ou
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql/:ro
volumes:
 db_data: {}

